[package]
name = "music-tagger"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.25"
env_logger = "0.11.6"
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
tempfile = "3.15.0"
id3 = "1.16.1"


